package awg

import "fmt"

// Paths are generated by Deploy from a validated interface and a random token.
// No config content is printed or passed as a command-line argument.
func backupConfigScript(iface, backupDir string) string {
	return fmt.Sprintf(`set -eu
umask 077
config=/etc/amnezia/amneziawg/%[1]s.conf
backup=%[2]s
mkdir -p /etc/amnezia/amneziawg
if [ -L "$config" ] || { [ -e "$config" ] && [ ! -f "$config" ]; }; then
  echo 'Refusing non-regular server configuration' >&2; exit 1
fi
if [ ! -f "$config" ] && { ip link show %[1]s >/dev/null 2>&1 || systemctl is-active --quiet awg-quick@%[1]s; }; then
  echo 'An existing tunnel has no managed configuration; refusing to replace it' >&2; exit 1
fi
mkdir -m700 "$backup"
if [ -f "$config" ]; then
  cp -- "$config" "$backup/previous.conf"
  chmod 600 "$backup/previous.conf"
  echo previous=1
else
  echo previous=0
fi`, iface, backupDir)
}

func activateConfigScript(iface, backupDir, digest string, hadPrevious bool) string {
	guard := `test ! -e "$config" && test ! -L "$config"`
	if hadPrevious {
		guard = `test -f "$config" && test ! -L "$config" && cmp -s "$config" "$backup/previous.conf"`
	}
	return fmt.Sprintf(`set -eu
config=/etc/amnezia/amneziawg/%[1]s.conf
backup=%[2]s
if ! { %[4]s; }; then
  echo 'Server configuration changed after backup; refusing to overwrite it' >&2; exit 1
fi
printf '%%s  %%s\n' '%[3]s' "$backup/new.conf" | sha256sum -c - >/dev/null
chmod 600 "$backup/new.conf"
mv -f -- "$backup/new.conf" "$config"
echo 'configuration activated'`, iface, backupDir, digest, guard)
}

func rollbackConfigScript(iface, backupDir, digest string, hadPrevious bool) string {
	previousGuard := "false"
	restore := `if [ -e "$config" ]; then rm -- "$config"; fi
echo 'new configuration removed'`
	if hadPrevious {
		previousGuard = `cmp -s "$config" "$backup/previous.conf"`
		restore = fmt.Sprintf(`test -f "$backup/previous.conf" && test ! -L "$backup/previous.conf"
cp -- "$backup/previous.conf" "$backup/restore.conf"
chmod 600 "$backup/restore.conf"
mv -f -- "$backup/restore.conf" "$config"
systemctl restart awg-quick@%[1]s
systemctl is-active --quiet awg-quick@%[1]s
awg show %[1]s listen-port | grep -Eq '^[1-9][0-9]*$'
echo 'previous configuration restored and running'`, iface)
	}
	return fmt.Sprintf(`set -eu
umask 077
config=/etc/amnezia/amneziawg/%[1]s.conf
backup=%[2]s
test -d "$backup" && test ! -L "$backup"
if [ -L "$config" ] || { [ -e "$config" ] && [ ! -f "$config" ]; }; then
  echo 'Rollback refused: configuration is no longer a regular file' >&2; exit 1
fi
if [ -f "$config" ]; then
  current=$(sha256sum "$config"); current=${current%%%% *}
  if [ "$current" != '%[3]s' ] && ! { %[4]s; }; then
    echo 'Rollback refused: another process changed the server configuration; backup retained' >&2; exit 1
  fi
fi
systemctl stop awg-quick@%[1]s >/dev/null 2>&1 || true
if ip link show %[1]s >/dev/null 2>&1; then
  if [ -f "$config" ]; then awg-quick down %[1]s; else ip link delete dev %[1]s; fi
fi
%[5]s`, iface, backupDir, digest, previousGuard, restore)
}

// Separate cleanup keeps the backup available if SSH is lost after recovery
// already ran. A new SSH session can safely repeat the rollback before cleanup.
func cleanupConfigBackupScript(backupDir string) string {
	return fmt.Sprintf(`set -eu
backup=%s
if [ ! -e "$backup" ]; then echo 'backup already removed'; exit 0; fi
test -d "$backup" && test ! -L "$backup"
rm -f -- "$backup/new.conf" "$backup/previous.conf" "$backup/restore.conf"
rmdir -- "$backup"
echo 'configuration backup removed'`, backupDir)
}
