package nfqws2

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	routerpath "nfqws2strategy/internal/tools/path"
	"nfqws2strategy/internal/tools/shell"
)

// The panel owns a helper separate from the upstream nfqws-bypass.sh. The
// upstream Entware helper resolves domains and runs iptables once per address,
// which can take minutes on a router. This POSIX-sh helper consumes the panel's
// resolved-IP cache and bulk-loads one dedicated mangle chain.
const generatedBypassScript = `#!/bin/sh
# Generated by nfqws2-strategy. Do not edit: upgraded with the panel.
set -u
set -f

CMD="${1:-iptables}"
case "$CMD" in
  iptables|ip6tables) ;;
  *) echo "usage: $0 {iptables|ip6tables}" >&2; exit 2 ;;
esac

TABLE=mangle
BYPASS=nfqws2_bypass
POST=nfqws_post
PRE=nfqws_pre
BASE=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)
LIST="$BASE/lists"

# Upstream omits IPv6 firewall chains when IPV6_ENABLED=0.  An absent IPv6
# family is normal; IPv4 below must still validate its bypass jumps.
if [ "$CMD" = ip6tables ] &&
   ! $CMD -w -t "$TABLE" -S "$POST" >/dev/null 2>&1 &&
   ! $CMD -w -t "$TABLE" -S "$PRE" >/dev/null 2>&1; then
  exit 0
fi

# A single iptables-restore commit replaces hundreds of iptables processes
# when the bypass list includes many CDN addresses. Only our dedicated chain
# is flushed; nfqws2's own chains and unrelated firewall rules stay intact.
if ! $CMD -w -t "$TABLE" -L "$BYPASS" -n >/dev/null 2>&1; then
  $CMD -w -t "$TABLE" -N "$BYPASS" || { echo "NFQUEUE bypass: cannot create $BYPASS" >&2; exit 1; }
fi
tmp=$(mktemp "${TMPDIR:-/tmp}/nfqws-bypass.XXXXXX") || exit 1
trap 'rm -f "$tmp"' 0 HUP INT TERM
printf '*%s\n:%s - [0:0]\n' "$TABLE" "$BYPASS" > "$tmp"

add_ip() {
  ip="$1"
  case "$ip" in
    *:*)
      [ "$CMD" = ip6tables ] || return 0
      printf '%s\n' "$ip" | grep -Eq '^[0-9A-Fa-f:]+(/[0-9]+)?$' || return 0
      ;;
    *.*)
      [ "$CMD" = iptables ] || return 0
      printf '%s\n' "$ip" | awk -F/ '{n=split($1,a,"."); if (n!=4) exit 1; for(i in a) if (a[i] !~ /^[0-9]+$/ || a[i] > 255) exit 1; if ($2 != "" && ($2 !~ /^[0-9]+$/ || $2 > 32)) exit 1}' || return 0
      ;;
    *) return 0 ;;
  esac
  # ACCEPT is deliberate: RETURN would resume the parent nfqws chain and
  # immediately hit its NFQUEUE rule.
  printf '%s\n' "-A $BYPASS -d $ip -j ACCEPT" "-A $BYPASS -s $ip -j ACCEPT" >> "$tmp"
}

# Domain resolution is done by the panel with bounded concurrency and written
# atomically to nfqueue_bypass_resolved.list. Keenetic executes this helper on
# every firewall rebuild, so DNS calls here would delay netfilter.
for file in "$LIST/nfqueue_bypass_ips.list" "$LIST/nfqueue_bypass_resolved.list"; do
  [ -r "$file" ] || continue
  while IFS= read -r raw || [ -n "$raw" ]; do
    # Strip comments and whitespace using shell builtins; this loop may read
    # hundreds of addresses on small routers.
    value=${raw%%#*}
    value=${value%%;*}
    set -- $value
    [ "$#" -eq 1 ] || continue
    add_ip "$1"
  done < "$file"
done

printf 'COMMIT\n' >> "$tmp"

apply_legacy() {
  # Very old builds may lack iptables-restore or --noflush. Keep a functional
  # fallback, though the bulk path is much faster for large lists.
  $CMD -w -t "$TABLE" -F "$BYPASS" || return 1
  while IFS= read -r rule; do
    case "$rule" in
      -A\ *)
        set -- $rule
        $CMD -w -t "$TABLE" "$@" || return 1
        ;;
    esac
  done < "$tmp"
}

RESTORE="${CMD}-restore"
if command -v "$RESTORE" >/dev/null 2>&1 &&
   "$RESTORE" --noflush < "$tmp"; then
  :
elif ! apply_legacy; then
  echo "NFQUEUE bypass: cannot install $CMD destination rules" >&2
  exit 1
fi

# Upstream flushes nfqws_pre/nfqws_post on every restart. Reinsert our jump at
# position 1 so it runs before all NFQUEUE rules, and reject partial installs.
for parent in "$POST" "$PRE"; do
  if ! $CMD -w -t "$TABLE" -L "$parent" -n >/dev/null 2>&1; then
    echo "NFQUEUE bypass: missing $CMD chain $parent" >&2
    exit 1
  fi
  while $CMD -w -t "$TABLE" -C "$parent" -j "$BYPASS" 2>/dev/null; do
    $CMD -w -t "$TABLE" -D "$parent" -j "$BYPASS" ||
      { echo "NFQUEUE bypass: cannot remove duplicate jump" >&2; exit 1; }
  done
  if ! $CMD -w -t "$TABLE" -I "$parent" 1 -j "$BYPASS" ||
     ! $CMD -w -t "$TABLE" -C "$parent" -j "$BYPASS"; then
    echo "NFQUEUE bypass: cannot attach $CMD jump $parent -> $BYPASS" >&2
    exit 1
  fi
done

exit 0
`

// ensureBypassScript creates or upgrades our generated helper. Vendor helpers
// are preserved; older generated versions must be replaced so fixes reach
// routers that already applied bypass under a previous panel release.
func ensureBypassScript(name string) error {
	if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		return err
	}
	if st, err := os.Stat(name); err == nil {
		if st.IsDir() {
			return os.ErrInvalid
		}
		current, err := os.ReadFile(name)
		if err != nil {
			return err
		}
		if !strings.HasPrefix(string(current), "#!/bin/sh\n# Generated by nfqws2-strategy.") {
			if filepath.Base(name) == "nfqws-strategy-bypass.sh" {
				return fmt.Errorf("NFQUEUE bypass helper %s was modified outside the panel", name)
			}
			return os.Chmod(name, 0o755)
		}
		if string(current) == generatedBypassScript {
			return os.Chmod(name, 0o755)
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(name), ".nfqws-bypass-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(generatedBypassScript); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o755); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), name)
}

// ensureBypassPersistence installs the bypass after the platform's firewall
// rebuild hook.  Keenetic runs netfilter.d hooks in lexical order, so 101 runs
// after nfqws2's 100-nfqws2.sh has recreated its own chains.  OpenWrt uses a
// firewall4 script include instead.
func ensureBypassPersistence(confDir, initScript, bypassScript string) error {
	if !routerpath.IsOpenWrt() {
		return ensureKeeneticBypassPersistence(confDir, bypassScript)
	}
	if _, err := exec.LookPath("uci"); err != nil {
		return nil
	}
	hook := routerpath.Path(routerpath.NFQWSBypassFW4)
	if hook == "" || filepath.Dir(hook) != confDir {
		hook = filepath.Join(confDir, "nfqws-bypass-fw4.sh")
	}
	body := fmt.Sprintf("#!/bin/sh\n%s firewall_iptables >/dev/null 2>&1 || true\n%s firewall_ip6tables >/dev/null 2>&1 || true\n%s iptables >/dev/null || echo 'NFQUEUE bypass: IPv4 firewall reload failed' >&2\n%s ip6tables >/dev/null || echo 'NFQUEUE bypass: IPv6 firewall reload failed' >&2\n",
		shell.Quote(initScript), shell.Quote(initScript), shell.Quote(bypassScript), shell.Quote(bypassScript))
	if err := os.WriteFile(hook, []byte(body), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(hook, 0o755); err != nil {
		return err
	}
	cmd := "uci -q show firewall.nfqws2_bypass_fw4 >/dev/null 2>&1 || uci set firewall.nfqws2_bypass_fw4=include; " +
		"uci set firewall.nfqws2_bypass_fw4.type=script; " +
		"uci set firewall.nfqws2_bypass_fw4.path=" + shell.Quote(filepath.ToSlash(hook)) + "; " +
		"uci set firewall.nfqws2_bypass_fw4.fw4_compatible=1; uci commit firewall"
	if out, err := exec.Command("sh", "-c", cmd).CombinedOutput(); err != nil {
		return fmt.Errorf("uci include: %v: %s", err, out)
	}
	return nil
}

const keeneticBypassHookName = "101-nfqws2-bypass.sh"

func keeneticBypassHookPath(confDir string) string {
	return filepath.Join(filepath.Dir(confDir), "ndm", "netfilter.d", keeneticBypassHookName)
}

func ensureKeeneticBypassPersistence(confDir, bypassScript string) error {
	hook := keeneticBypassHookPath(confDir)
	if err := os.MkdirAll(filepath.Dir(hook), 0o755); err != nil {
		return err
	}
	// The upstream 100-nfqws2.sh hook receives table/type from ndm and invokes
	// firewall_$type.  Run only for mangle, once those nfqws chains exist.  The
	// helper rebuilds both its jumps and destination rules idempotently.
	body := "#!/bin/sh\n" +
		"[ \"${table:-}\" = mangle ] || exit 0\n" +
		"case \"${type:-}\" in iptables|ip6tables) ;; *) exit 0 ;; esac\n" +
		"[ -x " + shell.Quote(bypassScript) + " ] || exit 0\n" +
		shell.Quote(bypassScript) + " \"$type\" >/dev/null || echo 'NFQUEUE bypass: Keenetic firewall reload failed' >&2\n"
	tmp, err := os.CreateTemp(filepath.Dir(hook), ".nfqws2-bypass-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(body); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o755); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), hook)
}

// ensureBypassInitHook keeps the dedicated jump alive across an NFQWS2
// restart on both OpenWrt and Keenetic.  Both upstream init scripts call
// system_config after rebuilding their firewall chains; the netfilter.d/fw4
// hooks only cover platform firewall reloads. Package updates are repaired by
// Manager.Update and the installer.
func ensureBypassInitHook(initScript, bypassScript string) error {
	return ensureBypassInitHookOn(initScript, bypassScript, true)
}

func ensureBypassInitHookOn(initScript, bypassScript string, enabled bool) error {
	if !enabled || initScript == "" || bypassScript == "" {
		return nil
	}
	b, err := os.ReadFile(initScript)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	const marker = "# nfqws2-strategy: reapply NFQUEUE bypass"
	text := string(b)
	line := marker + "\n[ -x " + shell.Quote(bypassScript) + " ] && " + shell.Quote(bypassScript) + " iptables >/dev/null 2>&1 || true\n[ -x " + shell.Quote(bypassScript) + " ] && " + shell.Quote(bypassScript) + " ip6tables >/dev/null 2>&1 || true"
	updated := ""
	if strings.Contains(text, marker) {
		// v1.6.5 and older pointed the tagged block at the vendor helper. Replace
		// only the two lines owned by this panel, keeping other init edits intact.
		lines := strings.SplitAfter(text, "\n")
		found := false
		for i, raw := range lines {
			if strings.TrimSpace(raw) != marker {
				continue
			}
			if i+2 >= len(lines) {
				return fmt.Errorf("NFQWS2 init has incomplete bypass hook")
			}
			for j, family := range []string{"iptables", "ip6tables"} {
				hookLine := strings.TrimSpace(lines[i+1+j])
				if !strings.HasPrefix(hookLine, "[ -x ") || !strings.Contains(hookLine, " ] && ") || !strings.Contains(hookLine, " "+family+" >/dev/null 2>&1 || true") {
					return fmt.Errorf("NFQWS2 init has unexpected bypass hook")
				}
			}
			oldBlock := lines[i] + lines[i+1] + lines[i+2]
			updated = strings.Replace(text, oldBlock, line+"\n", 1)
			found = true
			break
		}
		if !found {
			return fmt.Errorf("NFQWS2 init has unrecognized bypass marker")
		}
	} else {
		idx := -1
		offset := 0
		for _, raw := range strings.SplitAfter(text, "\n") {
			trimmed := strings.TrimSpace(raw)
			if strings.HasPrefix(trimmed, "system_config") && !strings.Contains(trimmed, "()") && !strings.HasSuffix(trimmed, "{") {
				idx = offset
				break
			}
			offset += len(raw)
		}
		if idx < 0 {
			return fmt.Errorf("NFQWS2 init has no system_config post-start anchor")
		}
		end := strings.IndexByte(text[idx:], '\n')
		if end < 0 {
			return fmt.Errorf("NFQWS2 init has malformed system_config line")
		}
		insertAt := idx + end + 1
		updated = text[:insertAt] + line + "\n" + text[insertAt:]
	}
	if updated == text {
		return nil
	}
	// Keep one pristine copy for rollback. The temporary replacement must have
	// a different name; otherwise a successful rename would remove the backup
	// and leave only the already patched script behind.
	backup := initScript + ".n2s-bak"
	if _, statErr := os.Stat(backup); os.IsNotExist(statErr) {
		file, createErr := os.OpenFile(backup, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o755)
		if createErr != nil && !os.IsExist(createErr) {
			return createErr
		}
		if createErr == nil {
			if _, writeErr := file.Write(b); writeErr != nil {
				_ = file.Close()
				_ = os.Remove(backup)
				return writeErr
			}
			if closeErr := file.Close(); closeErr != nil {
				_ = os.Remove(backup)
				return closeErr
			}
		}
		if err := os.Chmod(backup, 0o755); err != nil {
			return err
		}
	} else if statErr != nil {
		return statErr
	}
	tmpFile, err := os.CreateTemp(filepath.Dir(initScript), filepath.Base(initScript)+".n2s-new-")
	if err != nil {
		return err
	}
	tmp := tmpFile.Name()
	if _, err := tmpFile.Write([]byte(updated)); err != nil {
		_ = tmpFile.Close()
		_ = os.Remove(tmp)
		return err
	}
	if err := tmpFile.Close(); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Chmod(tmp, 0o755); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, initScript); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// removeBypassPersistence is used by the package uninstaller on both router
// families.  Only the hook owned by this package is removed.
func removeBypassPersistence(confDir string) {
	_ = os.Remove(filepath.Join(confDir, "nfqws-bypass-fw4.sh"))
	_ = os.Remove(keeneticBypassHookPath(confDir))
	if _, err := exec.LookPath("uci"); err == nil {
		_, _ = exec.Command("sh", "-c", "uci -q delete firewall.nfqws2_bypass_fw4 2>/dev/null || true; uci commit firewall 2>/dev/null || true").CombinedOutput()
	}
}
