package nfqws2

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"nfqws2strategy/internal/tools/shell"
)

// The upstream package has historically installed nfqws-bypass.sh only on
// Entware.  OpenWrt 25 APK packages omit it, while the web API still calls the
// helper when the user applies an NFQUEUE bypass list.  Keep the generated
// helper deliberately small and POSIX-sh compatible: it uses a dedicated
// mangle chain, so rebuilding nfqws2's own chains cannot leave stale rules.
const generatedBypassScript = `#!/bin/sh
# Generated by nfqws2-strategy. Do not edit: regenerated only when absent.
set -u

CMD="${1:-iptables}"
case "$CMD" in
  iptables|ip6tables) ;;
  *) echo "usage: $0 {iptables|ip6tables}" >&2; exit 2 ;;
esac

TABLE=mangle
BYPASS=nfqws2_bypass
POST=nfqws_post
PRE=nfqws_pre
BASE=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)
LIST="$BASE/lists"

# The command is intentionally idempotent.  The nfqws2 init script flushes
# nfqws_pre/nfqws_post on every restart; our dedicated chain survives that and
# is rebuilt below.  Remove duplicate jumps left by older helper versions.
$CMD -w -t "$TABLE" -N "$BYPASS" 2>/dev/null || true
$CMD -w -t "$TABLE" -F "$BYPASS" 2>/dev/null || true
for parent in "$POST" "$PRE"; do
  while $CMD -w -t "$TABLE" -C "$parent" -j "$BYPASS" 2>/dev/null; do
    $CMD -w -t "$TABLE" -D "$parent" -j "$BYPASS" 2>/dev/null || break
  done
  $CMD -w -t "$TABLE" -I "$parent" 1 -j "$BYPASS" 2>/dev/null || true
done

add_ip() {
  ip="$1"
  case "$ip" in
    *:*)
      [ "$CMD" = ip6tables ] || return 0
      printf '%s\n' "$ip" | grep -Eq '^[0-9A-Fa-f:]+(/[0-9]+)?$' || return 0
      ;;
    *.*)
      [ "$CMD" = iptables ] || return 0
      printf '%s\n' "$ip" | awk -F/ '{n=split($1,a,"."); if (n!=4) exit 1; for(i in a) if (a[i] !~ /^[0-9]+$/ || a[i] > 255) exit 1; if ($2 != "" && ($2 !~ /^[0-9]+$/ || $2 > 32)) exit 1}' || return 0
      ;;
    *) return 0 ;;
  esac
  # ACCEPT is deliberate: RETURN would resume the parent nfqws chain and
  # immediately hit its NFQUEUE rule.  A mangle ACCEPT skips that chain while
  # still allowing the packet through the later filter/NAT hooks.
  $CMD -w -t "$TABLE" -A "$BYPASS" -d "$ip" -j ACCEPT 2>/dev/null || true
  $CMD -w -t "$TABLE" -A "$BYPASS" -s "$ip" -j ACCEPT 2>/dev/null || true
}

resolve_host() {
  host="$1"
  case "$host" in
    *:*)
      # A colon is not sufficient to identify IPv6 (hostnames may contain one
      # in malformed input).  Accept only hexadecimal groups and an optional
      # CIDR suffix; otherwise let the resolver handle the value.
      if printf '%s\n' "$host" | grep -Eq '^[0-9A-Fa-f:]+(/[0-9]+)?$'; then
        add_ip "$host"; return 0
      fi
      ;;
    *.*)
      if printf '%s\n' "$host" | awk -F/ '{n=split($1,a,"."); if (n!=4) exit 1; for(i in a) if (a[i] !~ /^[0-9]+$/ || a[i] > 255) exit 1; if ($2 != "" && ($2 !~ /^[0-9]+$/ || $2 > 32)) exit 1}' ; then
        add_ip "$host"; return 0
      fi
      ;;
  esac
  # BusyBox builds differ: prefer getent, then nslookup.  Only accept an IP
  # token, so resolver diagnostics cannot become an iptables argument.
  resolved=0
  if command -v getent >/dev/null 2>&1; then
    answers=$(getent "$([ "$CMD" = ip6tables ] && echo ahostsv6 || echo ahostsv4)" "$host" 2>/dev/null || true)
    if [ -n "$answers" ]; then
      printf '%s\n' "$answers" | awk '{print $1}' | while IFS= read -r ip; do add_ip "$ip"; done
      resolved=1
    fi
  fi
  if [ "$resolved" -eq 0 ] && command -v nslookup >/dev/null 2>&1; then
    # BusyBox nslookup prints the resolver address first; skip it so a local
    # DNS address never becomes a bypass destination.
    nslookup "$host" 2>/dev/null | awk '/^Address([ 0-9]*:)?[ 	]+/ {if (++n > 1) print $NF}' |
      while IFS= read -r ip; do add_ip "$ip"; done
  fi
}

for file in "$LIST/nfqueue_bypass_ips.list" "$LIST/nfqueue_bypass_domains.list"; do
  [ -r "$file" ] || continue
  while IFS= read -r raw || [ -n "$raw" ]; do
    # Strip comments and surrounding whitespace.  Domain/IP lists are user
    # editable, so ignore malformed lines rather than breaking firewall setup.
    value=$(printf '%s\n' "$raw" | sed 's/[#;].*$//' | awk '{$1=$1; print}')
    [ -n "$value" ] || continue
    case "$file" in
      *nfqueue_bypass_ips.list) add_ip "$value" ;;
      *) resolve_host "$value" ;;
    esac
  done < "$file"
done

exit 0
`

// ensureBypassScript creates the OpenWrt-safe fallback helper when the package
// did not include one.  chmod is attempted for an existing helper too because
// APK extraction can preserve a non-executable mode on overlayfs.
func ensureBypassScript(name string) error {
	if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		return err
	}
	if st, err := os.Stat(name); err == nil {
		if st.IsDir() {
			return os.ErrInvalid
		}
		return os.Chmod(name, 0o755)
	} else if !os.IsNotExist(err) {
		return err
	}
	tmp := name + ".new"
	if err := os.WriteFile(tmp, []byte(generatedBypassScript), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(tmp, 0o755); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, name); err != nil {
		_ = os.Remove(tmp)
		// Another process may have won the race.  Preserve that helper.
		if st, statErr := os.Stat(name); statErr == nil && !st.IsDir() {
			return os.Chmod(name, 0o755)
		}
		return err
	}
	return nil
}

// ensureBypassPersistence registers the bypass helper as an OpenWrt firewall4
// script include.  fw4 recreates the compatibility chains during every reload;
// without this hook the API appears to apply successfully but the next reload
// silently drops the bypass jump.  Entware/Keenetic has its own netfilter hook
// lifecycle and is intentionally left untouched.
func ensureBypassPersistence(confDir, initScript, bypassScript string) error {
	if _, err := os.Stat("/etc/openwrt_release"); err != nil {
		if _, err = os.Stat("/etc/rc.common"); err != nil {
			return nil
		}
	}
	if _, err := exec.LookPath("uci"); err != nil {
		return nil
	}
	hook := filepath.Join(confDir, "nfqws-bypass-fw4.sh")
	body := fmt.Sprintf("#!/bin/sh\n%s firewall_iptables >/dev/null 2>&1 || true\n%s iptables >/dev/null 2>&1 || true\n", shell.Quote(initScript), shell.Quote(bypassScript))
	if err := os.WriteFile(hook, []byte(body), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(hook, 0o755); err != nil {
		return err
	}
	cmd := "uci -q show firewall.nfqws2_bypass_fw4 >/dev/null 2>&1 || uci set firewall.nfqws2_bypass_fw4=include; " +
		"uci set firewall.nfqws2_bypass_fw4.type=script; " +
		"uci set firewall.nfqws2_bypass_fw4.path=" + shell.Quote(filepath.ToSlash(hook)) + "; " +
		"uci set firewall.nfqws2_bypass_fw4.fw4_compatible=1; uci commit firewall"
	if out, err := exec.Command("sh", "-c", cmd).CombinedOutput(); err != nil {
		return fmt.Errorf("uci include: %v: %s", err, out)
	}
	return nil
}

// removeBypassPersistence is used by the package uninstaller and is safe on
// non-OpenWrt hosts.
func removeBypassPersistence(confDir string) {
	_ = os.Remove(filepath.Join(confDir, "nfqws-bypass-fw4.sh"))
	if _, err := exec.LookPath("uci"); err == nil {
		_, _ = exec.Command("sh", "-c", "uci -q delete firewall.nfqws2_bypass_fw4 2>/dev/null || true; uci commit firewall 2>/dev/null || true").CombinedOutput()
	}
}
