package nfqws2

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"nfqws2strategy/internal/tools/shell"
)

func TestEnsureBypassScriptCreatesExecutableFallback(t *testing.T) {
	dir := t.TempDir()
	name := filepath.Join(dir, "nfqws2", "nfqws-bypass.sh")
	if err := ensureBypassScript(name); err != nil {
		t.Fatal(err)
	}
	st, err := os.Stat(name)
	if err != nil {
		t.Fatal(err)
	}
	if runtime.GOOS != "windows" && st.Mode().Perm()&0o111 == 0 {
		t.Fatalf("fallback is not executable: %v", st.Mode())
	}
	data, err := os.ReadFile(name)
	if err != nil {
		t.Fatal(err)
	}
	for _, needle := range []string{"nfqws2_bypass", "nfqws_post", "nfqws_pre", "nfqueue_bypass_resolved.list", "-j ACCEPT"} {
		if !strings.Contains(string(data), needle) {
			t.Errorf("fallback script missing %q", needle)
		}
	}
	if strings.Contains(string(data), "nslookup") || strings.Contains(string(data), "getent") {
		t.Fatal("firewall hook must use the resolved IP cache without DNS queries")
	}
}

func TestEnsureBypassScriptUpgradesOnlyGeneratedHelper(t *testing.T) {
	dir := t.TempDir()
	name := filepath.Join(dir, "nfqws-strategy-bypass.sh")
	old := "#!/bin/sh\n# Generated by nfqws2-strategy. Do not edit.\nexit 0\n"
	if err := os.WriteFile(name, []byte(old), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := ensureBypassScript(name); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(name)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != generatedBypassScript {
		t.Fatal("old generated helper was not upgraded")
	}
	if err := ensureBypassScript(name); err != nil {
		t.Fatal(err)
	}
	again, err := os.ReadFile(name)
	if err != nil || string(again) != string(got) {
		t.Fatalf("helper upgrade is not idempotent: %v", err)
	}
}

func TestEnsureBypassScriptPreservesVendorHelper(t *testing.T) {
	dir := t.TempDir()
	name := filepath.Join(dir, "nfqws-bypass.sh")
	const vendor = "#!/bin/sh\necho vendor\n"
	if err := os.WriteFile(name, []byte(vendor), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := ensureBypassScript(name); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(name)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != vendor {
		t.Fatalf("vendor helper overwritten: %q", data)
	}
	if st, err := os.Stat(name); err != nil || (runtime.GOOS != "windows" && st.Mode().Perm()&0o111 == 0) {
		t.Fatalf("vendor helper was not made executable: %v", err)
	}
}

func TestEnsureBypassScriptRefusesModifiedOwnedHelper(t *testing.T) {
	name := filepath.Join(t.TempDir(), "nfqws-strategy-bypass.sh")
	const external = "#!/bin/sh\necho custom\n"
	if err := os.WriteFile(name, []byte(external), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := ensureBypassScript(name); err == nil {
		t.Fatal("modified panel-owned helper must not run silently")
	}
	data, err := os.ReadFile(name)
	if err != nil || string(data) != external {
		t.Fatalf("modified helper was changed: %q err=%v", data, err)
	}
}

func TestEnsureBypassInitHookIsIdempotentAndPostSystemConfig(t *testing.T) {
	dir := t.TempDir()
	init := filepath.Join(dir, "S51nfqws2")
	bypass := filepath.Join(dir, "nfqws-bypass.sh")
	const source = "#!/bin/sh\nstart_service() {\n  firewall_iptables\n  system_config\n}\n"
	if err := os.WriteFile(init, []byte(source), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := ensureBypassInitHook(init, bypass); err != nil {
		t.Fatal(err)
	}
	first, err := os.ReadFile(init)
	if err != nil {
		t.Fatal(err)
	}
	text := string(first)
	marker := "# nfqws2-strategy: reapply NFQUEUE bypass"
	if strings.Count(text, marker) != 1 || strings.Index(text, marker) <= strings.Index(text, "system_config") {
		t.Fatalf("hook placement is wrong: %q", text)
	}
	backup, err := os.ReadFile(init + ".n2s-bak")
	if err != nil {
		t.Fatalf("original init backup missing: %v", err)
	}
	if string(backup) != source {
		t.Fatalf("init backup was not pristine: %q", backup)
	}
	if err := ensureBypassInitHook(init, bypass); err != nil {
		t.Fatal(err)
	}
	second, err := os.ReadFile(init)
	if err != nil {
		t.Fatal(err)
	}
	if string(second) != text {
		t.Fatal("second application changed an already patched init script")
	}
}

func TestEnsureBypassInitHookLeavesDisabledTargetUntouched(t *testing.T) {
	dir := t.TempDir()
	init := filepath.Join(dir, "nfqws2-keenetic")
	const source = "#!/bin/sh\nsystem_config\n"
	if err := os.WriteFile(init, []byte(source), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := ensureBypassInitHookOn(init, filepath.Join(dir, "bypass"), false); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(init)
	if string(got) != source {
		t.Fatal("disabled init script was modified")
	}
}

func TestEnsureBypassInitHookMigratesOldVendorPath(t *testing.T) {
	dir := t.TempDir()
	init := filepath.Join(dir, "S51nfqws2")
	oldHelper := filepath.Join(dir, "nfqws-bypass.sh")
	newHelper := filepath.Join(dir, "nfqws-strategy-bypass.sh")
	const marker = "# nfqws2-strategy: reapply NFQUEUE bypass"
	source := "#!/bin/sh\nstart() {\n  system_config\n" + marker + "\n" +
		"[ -x " + shell.Quote(oldHelper) + " ] && " + shell.Quote(oldHelper) + " iptables >/dev/null 2>&1 || true\n" +
		"[ -x " + shell.Quote(oldHelper) + " ] && " + shell.Quote(oldHelper) + " ip6tables >/dev/null 2>&1 || true\n}\n"
	if err := os.WriteFile(init, []byte(source), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := ensureBypassInitHook(init, newHelper); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(init)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(got), shell.Quote(oldHelper)) || strings.Count(string(got), marker) != 1 || strings.Count(string(got), shell.Quote(newHelper)) != 4 {
		t.Fatalf("legacy init hook was not migrated: %q", got)
	}
	if err := ensureBypassInitHook(init, newHelper); err != nil {
		t.Fatal(err)
	}
	again, err := os.ReadFile(init)
	if err != nil || string(again) != string(got) {
		t.Fatalf("migrated hook changed on second apply: %v", err)
	}
}

func TestKeeneticBypassHookRunsOnlyAfterMangleRebuild(t *testing.T) {
	root := t.TempDir()
	confDir := filepath.Join(root, "opt", "etc", "nfqws2")
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		t.Fatal(err)
	}
	logFile := filepath.Join(root, "calls.txt")
	bypass := filepath.Join(confDir, "nfqws-bypass.sh")
	if err := os.WriteFile(bypass, []byte("#!/bin/sh\nprintf '%s\\n' \"$1\" >> "+shell.Quote(logFile)+"\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := ensureKeeneticBypassPersistence(confDir, bypass); err != nil {
		t.Fatal(err)
	}
	hook := keeneticBypassHookPath(confDir)
	if got := filepath.Base(hook); got != "101-nfqws2-bypass.sh" {
		t.Fatalf("hook must sort after upstream 100-nfqws2.sh: %q", got)
	}
	first, err := os.ReadFile(hook)
	if err != nil {
		t.Fatal(err)
	}
	if err := ensureKeeneticBypassPersistence(confDir, bypass); err != nil {
		t.Fatal(err)
	}
	second, err := os.ReadFile(hook)
	if err != nil || string(first) != string(second) {
		t.Fatalf("idempotent hook rewrite changed content: %v", err)
	}
	if runtime.GOOS == "windows" {
		return // POSIX hook is exercised in Linux CI and on the router.
	}
	if st, err := os.Stat(hook); err != nil || st.Mode().Perm()&0o111 == 0 {
		t.Fatalf("hook must be executable: %v", err)
	}
	for _, tc := range []struct {
		table, family string
	}{
		{"filter", "iptables"},
		{"mangle", "iptables"},
		{"nat", "ip6tables"},
		{"mangle", "ip6tables"},
		{"mangle", "unsupported"},
	} {
		cmd := exec.Command("sh", hook)
		cmd.Env = append(os.Environ(), "table="+tc.table, "type="+tc.family)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("hook %s/%s: %v: %s", tc.table, tc.family, err, out)
		}
	}
	got, err := os.ReadFile(logFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "iptables\nip6tables\n" {
		t.Fatalf("hook called helper for wrong firewall events: %q", got)
	}
	if err := os.WriteFile(bypass, []byte("#!/bin/sh\necho helper-error >&2\nexit 1\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("sh", hook)
	cmd.Env = append(os.Environ(), "table=mangle", "type=iptables")
	if out, err := cmd.CombinedOutput(); err != nil || !strings.Contains(string(out), "helper-error") || !strings.Contains(string(out), "firewall reload failed") {
		t.Fatalf("failed hook was not reported without aborting firewall reload: %v: %s", err, out)
	}
}

func TestGeneratedBypassReportsMissingIPv4JumpButAllowsDisabledIPv6(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("requires POSIX sh")
	}
	dir := t.TempDir()
	binDir := filepath.Join(dir, "bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"iptables", "ip6tables"} {
		if err := os.WriteFile(filepath.Join(binDir, name), []byte("#!/bin/sh\nexit 1\n"), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	helper := filepath.Join(dir, "nfqws-bypass.sh")
	if err := os.WriteFile(helper, []byte(generatedBypassScript), 0o755); err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct {
		family, want string
	}{
		{"iptables", "NFQUEUE bypass: cannot create"},
		{"ip6tables", ""},
	} {
		cmd := exec.Command("sh", helper, tc.family)
		cmd.Env = append(os.Environ(), "PATH="+binDir+string(os.PathListSeparator)+os.Getenv("PATH"))
		out, err := cmd.CombinedOutput()
		if tc.want == "" {
			if err != nil {
				t.Fatalf("disabled IPv6 should be allowed: %v: %s", err, out)
			}
		} else if err == nil || !strings.Contains(string(out), tc.want) {
			t.Fatalf("missing IPv4 bypass chain was not reported: %v: %s", err, out)
		}
	}
}

func TestGeneratedBypassUsesResolvedCacheAndBulkRestore(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("requires POSIX sh")
	}
	dir := t.TempDir()
	listDir := filepath.Join(dir, "lists")
	binDir := filepath.Join(dir, "bin")
	for _, path := range []string{listDir, binDir} {
		if err := os.MkdirAll(path, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	for name, body := range map[string]string{
		"nfqueue_bypass_ips.list":      "# direct IP\n192.0.2.1\n",
		"nfqueue_bypass_domains.list":  "img.reg.ru\n",
		"nfqueue_bypass_resolved.list": "203.0.113.10\nimg.reg.ru\n2001:db8::1\n",
	} {
		if err := os.WriteFile(filepath.Join(listDir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	help := filepath.Join(dir, "nfqws-strategy-bypass.sh")
	if err := os.WriteFile(help, []byte(generatedBypassScript), 0o755); err != nil {
		t.Fatal(err)
	}
	stateDir := filepath.Join(dir, "state")
	if err := os.MkdirAll(stateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	restoreStream := filepath.Join(dir, "restore.txt")
	iptablesMock := "#!/bin/sh\n" +
		"case \"$4\" in\n" +
		"  -L) exit 0 ;;\n" +
		"  -C) test -f " + shell.Quote(stateDir) + "/\"$5\"; exit $? ;;\n" +
		"  -D) rm -f " + shell.Quote(stateDir) + "/\"$5\"; exit 0 ;;\n" +
		"  -I) : > " + shell.Quote(stateDir) + "/\"$5\"; exit 0 ;;\n" +
		"esac\nexit 0\n"
	if err := os.WriteFile(filepath.Join(binDir, "iptables"), []byte(iptablesMock), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(binDir, "iptables-restore"), []byte("#!/bin/sh\ncat > "+shell.Quote(restoreStream)+"\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("sh", help, "iptables")
	cmd.Env = append(os.Environ(), "PATH="+binDir+string(os.PathListSeparator)+os.Getenv("PATH"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("bulk helper failed: %v: %s", err, out)
	}
	stream, err := os.ReadFile(restoreStream)
	if err != nil {
		t.Fatal(err)
	}
	got := string(stream)
	if !strings.HasPrefix(got, "*mangle\n:nfqws2_bypass - [0:0]\n") ||
		!strings.HasSuffix(got, "COMMIT\n") ||
		strings.Count(got, "-A nfqws2_bypass") != 4 ||
		strings.Contains(got, "img.reg.ru") ||
		strings.Contains(got, "2001:db8::1") {
		t.Fatalf("unexpected IPv4 restore stream: %q", got)
	}
	for _, parent := range []string{"nfqws_post", "nfqws_pre"} {
		if _, err := os.Stat(filepath.Join(stateDir, parent)); err != nil {
			t.Fatalf("%s jump was not inserted: %v", parent, err)
		}
	}
}

func TestGeneratedBypassFallsBackWhenRestoreUnsupported(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("requires POSIX sh")
	}
	dir := t.TempDir()
	for _, sub := range []string{"bin", "lists", "state"} {
		if err := os.MkdirAll(filepath.Join(dir, sub), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "lists", "nfqueue_bypass_resolved.list"), []byte("203.0.113.10\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	helper := filepath.Join(dir, "nfqws-strategy-bypass.sh")
	if err := os.WriteFile(helper, []byte(generatedBypassScript), 0o755); err != nil {
		t.Fatal(err)
	}
	stateDir := filepath.Join(dir, "state")
	logFile := filepath.Join(dir, "iptables.log")
	iptablesMock := "#!/bin/sh\n" +
		"printf '%s\\n' \"$*\" >> " + shell.Quote(logFile) + "\n" +
		"case \"$4\" in\n" +
		"  -L) exit 0 ;;\n" +
		"  -C) test -f " + shell.Quote(stateDir) + "/\"$5\"; exit $? ;;\n" +
		"  -D) rm -f " + shell.Quote(stateDir) + "/\"$5\"; exit 0 ;;\n" +
		"  -I) : > " + shell.Quote(stateDir) + "/\"$5\"; exit 0 ;;\n" +
		"esac\nexit 0\n"
	if err := os.WriteFile(filepath.Join(dir, "bin", "iptables"), []byte(iptablesMock), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "bin", "iptables-restore"), []byte("#!/bin/sh\nexit 1\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("sh", helper, "iptables")
	cmd.Env = append(os.Environ(), "PATH="+filepath.Join(dir, "bin")+string(os.PathListSeparator)+os.Getenv("PATH"))
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("fallback helper failed: %v: %s", err, out)
	}
	log, err := os.ReadFile(logFile)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"-F nfqws2_bypass",
		"-A nfqws2_bypass -d 203.0.113.10 -j ACCEPT",
		"-A nfqws2_bypass -s 203.0.113.10 -j ACCEPT",
		"-I nfqws_post 1 -j nfqws2_bypass",
		"-I nfqws_pre 1 -j nfqws2_bypass",
	} {
		if !strings.Contains(string(log), want) {
			t.Fatalf("legacy fallback omitted %q: %s", want, log)
		}
	}
}
