package nfqws2

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	routerpath "nfqws2strategy/internal/tools/path"
	"nfqws2strategy/internal/tools/shell"
)

// The upstream package has historically installed nfqws-bypass.sh only on
// Entware.  OpenWrt 25 APK packages omit it, while the web API still calls the
// helper when the user applies an NFQUEUE bypass list.  Keep the generated
// helper deliberately small and POSIX-sh compatible: it uses a dedicated
// mangle chain, so rebuilding nfqws2's own chains cannot leave stale rules.
const generatedBypassScript = `#!/bin/sh
# Generated by nfqws2-strategy. Do not edit: regenerated only when absent.
set -u

CMD="${1:-iptables}"
case "$CMD" in
  iptables|ip6tables) ;;
  *) echo "usage: $0 {iptables|ip6tables}" >&2; exit 2 ;;
esac

TABLE=mangle
BYPASS=nfqws2_bypass
POST=nfqws_post
PRE=nfqws_pre
BASE=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)
LIST="$BASE/lists"

# The command is intentionally idempotent.  The nfqws2 init script flushes
# nfqws_pre/nfqws_post on every restart; our dedicated chain survives that and
# is rebuilt below.  Remove duplicate jumps left by older helper versions.
$CMD -w -t "$TABLE" -N "$BYPASS" 2>/dev/null || true
$CMD -w -t "$TABLE" -F "$BYPASS" 2>/dev/null || true
for parent in "$POST" "$PRE"; do
  while $CMD -w -t "$TABLE" -C "$parent" -j "$BYPASS" 2>/dev/null; do
    $CMD -w -t "$TABLE" -D "$parent" -j "$BYPASS" 2>/dev/null || break
  done
  $CMD -w -t "$TABLE" -I "$parent" 1 -j "$BYPASS" 2>/dev/null || true
done

add_ip() {
  ip="$1"
  case "$ip" in
    *:*)
      [ "$CMD" = ip6tables ] || return 0
      printf '%s\n' "$ip" | grep -Eq '^[0-9A-Fa-f:]+(/[0-9]+)?$' || return 0
      ;;
    *.*)
      [ "$CMD" = iptables ] || return 0
      printf '%s\n' "$ip" | awk -F/ '{n=split($1,a,"."); if (n!=4) exit 1; for(i in a) if (a[i] !~ /^[0-9]+$/ || a[i] > 255) exit 1; if ($2 != "" && ($2 !~ /^[0-9]+$/ || $2 > 32)) exit 1}' || return 0
      ;;
    *) return 0 ;;
  esac
  # ACCEPT is deliberate: RETURN would resume the parent nfqws chain and
  # immediately hit its NFQUEUE rule.  A mangle ACCEPT skips that chain while
  # still allowing the packet through the later filter/NAT hooks.
  $CMD -w -t "$TABLE" -A "$BYPASS" -d "$ip" -j ACCEPT 2>/dev/null || true
  $CMD -w -t "$TABLE" -A "$BYPASS" -s "$ip" -j ACCEPT 2>/dev/null || true
}

resolve_host() {
  host="$1"
  case "$host" in
    *:*)
      # A colon is not sufficient to identify IPv6 (hostnames may contain one
      # in malformed input).  Accept only hexadecimal groups and an optional
      # CIDR suffix; otherwise let the resolver handle the value.
      if printf '%s\n' "$host" | grep -Eq '^[0-9A-Fa-f:]+(/[0-9]+)?$'; then
        add_ip "$host"; return 0
      fi
      ;;
    *.*)
      if printf '%s\n' "$host" | awk -F/ '{n=split($1,a,"."); if (n!=4) exit 1; for(i in a) if (a[i] !~ /^[0-9]+$/ || a[i] > 255) exit 1; if ($2 != "" && ($2 !~ /^[0-9]+$/ || $2 > 32)) exit 1}' ; then
        add_ip "$host"; return 0
      fi
      ;;
  esac
  # BusyBox builds differ: prefer getent, then nslookup.  Only accept an IP
  # token, so resolver diagnostics cannot become an iptables argument.
  resolved=0
  if command -v getent >/dev/null 2>&1; then
    answers=$(getent "$([ "$CMD" = ip6tables ] && echo ahostsv6 || echo ahostsv4)" "$host" 2>/dev/null || true)
    if [ -n "$answers" ]; then
      printf '%s\n' "$answers" | awk '{print $1}' | while IFS= read -r ip; do add_ip "$ip"; done
      resolved=1
    fi
  fi
  if [ "$resolved" -eq 0 ] && command -v nslookup >/dev/null 2>&1; then
    # BusyBox nslookup prints the resolver address first; skip it so a local
    # DNS address never becomes a bypass destination.
    nslookup "$host" 2>/dev/null | awk '/^Address([ 0-9]*:)?[ 	]+/ {if (++n > 1) print $NF}' |
      while IFS= read -r ip; do add_ip "$ip"; done
  fi
}

for file in "$LIST/nfqueue_bypass_ips.list" "$LIST/nfqueue_bypass_domains.list"; do
  [ -r "$file" ] || continue
  while IFS= read -r raw || [ -n "$raw" ]; do
    # Strip comments and surrounding whitespace.  Domain/IP lists are user
    # editable, so ignore malformed lines rather than breaking firewall setup.
    value=$(printf '%s\n' "$raw" | sed 's/[#;].*$//' | awk '{$1=$1; print}')
    [ -n "$value" ] || continue
    case "$file" in
      *nfqueue_bypass_ips.list) add_ip "$value" ;;
      *) resolve_host "$value" ;;
    esac
  done < "$file"
done

exit 0
`

// ensureBypassScript creates the OpenWrt-safe fallback helper when the package
// did not include one.  chmod is attempted for an existing helper too because
// APK extraction can preserve a non-executable mode on overlayfs.
func ensureBypassScript(name string) error {
	if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		return err
	}
	if st, err := os.Stat(name); err == nil {
		if st.IsDir() {
			return os.ErrInvalid
		}
		return os.Chmod(name, 0o755)
	} else if !os.IsNotExist(err) {
		return err
	}
	tmp := name + ".new"
	if err := os.WriteFile(tmp, []byte(generatedBypassScript), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(tmp, 0o755); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, name); err != nil {
		_ = os.Remove(tmp)
		// Another process may have won the race.  Preserve that helper.
		if st, statErr := os.Stat(name); statErr == nil && !st.IsDir() {
			return os.Chmod(name, 0o755)
		}
		return err
	}
	return nil
}

// ensureBypassPersistence registers the bypass helper as an OpenWrt firewall4
// script include.  fw4 recreates the compatibility chains during every reload;
// without this hook the API appears to apply successfully but the next reload
// silently drops the bypass jump.  Entware/Keenetic has its own netfilter hook
// lifecycle and is intentionally left untouched.
func ensureBypassPersistence(confDir, initScript, bypassScript string) error {
	if !routerpath.IsOpenWrt() {
		return nil
	}
	if _, err := exec.LookPath("uci"); err != nil {
		return nil
	}
	hook := routerpath.Path(routerpath.NFQWSBypassFW4)
	if hook == "" || filepath.Dir(hook) != confDir {
		hook = filepath.Join(confDir, "nfqws-bypass-fw4.sh")
	}
	body := fmt.Sprintf("#!/bin/sh\n%s firewall_iptables >/dev/null 2>&1 || true\n%s iptables >/dev/null 2>&1 || true\n", shell.Quote(initScript), shell.Quote(bypassScript))
	if err := os.WriteFile(hook, []byte(body), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(hook, 0o755); err != nil {
		return err
	}
	cmd := "uci -q show firewall.nfqws2_bypass_fw4 >/dev/null 2>&1 || uci set firewall.nfqws2_bypass_fw4=include; " +
		"uci set firewall.nfqws2_bypass_fw4.type=script; " +
		"uci set firewall.nfqws2_bypass_fw4.path=" + shell.Quote(filepath.ToSlash(hook)) + "; " +
		"uci set firewall.nfqws2_bypass_fw4.fw4_compatible=1; uci commit firewall"
	if out, err := exec.Command("sh", "-c", cmd).CombinedOutput(); err != nil {
		return fmt.Errorf("uci include: %v: %s", err, out)
	}
	return nil
}

// ensureBypassInitHook keeps the dedicated jump alive across an NFQWS2
// restart. The upstream init recreates nfqws_pre/nfqws_post after every
// firewall_iptables call, while the fw4 UCI include only covers firewall
// reloads. Patch one idempotent post-start line once; package updates are
// repaired by Manager.Update and the installer.
func ensureBypassInitHook(initScript, bypassScript string) error {
	return ensureBypassInitHookOn(initScript, bypassScript, routerpath.IsOpenWrt())
}

func ensureBypassInitHookOn(initScript, bypassScript string, openwrt bool) error {
	if !openwrt || initScript == "" || bypassScript == "" {
		return nil
	}
	b, err := os.ReadFile(initScript)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	const marker = "# nfqws2-strategy: reapply NFQUEUE bypass"
	if strings.Contains(string(b), marker) {
		return nil
	}
	text := string(b)
	line := marker + "\n[ -x " + shell.Quote(bypassScript) + " ] && " + shell.Quote(bypassScript) + " iptables >/dev/null 2>&1 || true\n[ -x " + shell.Quote(bypassScript) + " ] && " + shell.Quote(bypassScript) + " ip6tables >/dev/null 2>&1 || true"
	idx := -1
	offset := 0
	for _, raw := range strings.SplitAfter(text, "\n") {
		trimmed := strings.TrimSpace(raw)
		if strings.HasPrefix(trimmed, "system_config") && !strings.Contains(trimmed, "()") && !strings.HasSuffix(trimmed, "{") {
			idx = offset
			break
		}
		offset += len(raw)
	}
	if idx < 0 {
		return fmt.Errorf("NFQWS2 init has no system_config post-start anchor")
	}
	end := strings.IndexByte(text[idx:], '\n')
	if end < 0 {
		return fmt.Errorf("NFQWS2 init has malformed system_config line")
	}
	insertAt := idx + end + 1
	updated := text[:insertAt] + line + "\n" + text[insertAt:]
	// Keep one pristine copy for rollback. The temporary replacement must have
	// a different name; otherwise a successful rename would remove the backup
	// and leave only the already patched script behind.
	backup := initScript + ".n2s-bak"
	if _, statErr := os.Stat(backup); os.IsNotExist(statErr) {
		file, createErr := os.OpenFile(backup, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o755)
		if createErr != nil && !os.IsExist(createErr) {
			return createErr
		}
		if createErr == nil {
			if _, writeErr := file.Write(b); writeErr != nil {
				_ = file.Close()
				_ = os.Remove(backup)
				return writeErr
			}
			if closeErr := file.Close(); closeErr != nil {
				_ = os.Remove(backup)
				return closeErr
			}
		}
		if err := os.Chmod(backup, 0o755); err != nil {
			return err
		}
	} else if statErr != nil {
		return statErr
	}
	tmpFile, err := os.CreateTemp(filepath.Dir(initScript), filepath.Base(initScript)+".n2s-new-")
	if err != nil {
		return err
	}
	tmp := tmpFile.Name()
	if _, err := tmpFile.Write([]byte(updated)); err != nil {
		_ = tmpFile.Close()
		_ = os.Remove(tmp)
		return err
	}
	if err := tmpFile.Close(); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Chmod(tmp, 0o755); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, initScript); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// removeBypassPersistence is used by the package uninstaller and is safe on
// non-OpenWrt hosts.
func removeBypassPersistence(confDir string) {
	_ = os.Remove(filepath.Join(confDir, "nfqws-bypass-fw4.sh"))
	if _, err := exec.LookPath("uci"); err == nil {
		_, _ = exec.Command("sh", "-c", "uci -q delete firewall.nfqws2_bypass_fw4 2>/dev/null || true; uci commit firewall 2>/dev/null || true").CombinedOutput()
	}
}
